spring:
  influxdb:
    url: http://localhost:8086
    username: user
    password: user
    database: test
    retention-policy: autogen
    gzip: true
server:
  port: 9090
  compression:
    enabled: true
    min-reponse-size: 1025

---
spring:
  profiles: docker-compose
  influxdb:
    url: http://influxdb:8086
    username: user
    password: user
    database: test
    retention-policy: autogen
    gzip: true