spring:
  influxdb:
    url: http://localhost:8086
    username: user
    password: user
    database: test
    retention-policy: autogen
  cloud:
    stream:
      bindings:
        input:
          destination: iot.edge.topic
          binder: rabbit
          group: timeseries-sensor-consumer-group
      rabbit:
        bindings:
          input:
            consumer:
              queueNameGroupOnly: true
  rabbitmq:
    host: localhost
    password: admin
    username: admin